package com.vector.pojo;
// Generated 2019-4-19 9:49:57 by Hibernate Tools 4.3.1



/**
 * BackpackSetting generated by hbm2java
 */
public class BackpackSetting  implements java.io.Serializable {


     private Integer backpackSettingId;
     private String environmentPath;
     private String backpackToPath;

    public BackpackSetting() {
    }

    public BackpackSetting(String environmentPath, String backpackToPath) {
       this.environmentPath = environmentPath;
       this.backpackToPath = backpackToPath;
    }
   
    public Integer getBackpackSettingId() {
        return this.backpackSettingId;
    }
    
    public void setBackpackSettingId(Integer backpackSettingId) {
        this.backpackSettingId = backpackSettingId;
    }
    public String getEnvironmentPath() {
        return this.environmentPath;
    }
    
    public void setEnvironmentPath(String environmentPath) {
        this.environmentPath = environmentPath;
    }
    public String getBackpackToPath() {
        return this.backpackToPath;
    }
    
    public void setBackpackToPath(String backpackToPath) {
        this.backpackToPath = backpackToPath;
    }




}


