package com.vector.pojo;
// Generated 2019-3-22 22:17:21 by Hibernate Tools 4.3.1



/**
 * BackpackSetting generated by hbm2java
 */
public class BackpackSetting  implements java.io.Serializable {


     private Integer backpackSettingId;
     private String backpackSqlFile;
     private String backpackBatFile;
     private String backpackToPath;

    public BackpackSetting() {
    }

    public BackpackSetting(String backpackSqlFile, String backpackBatFile, String backpackToPath) {
       this.backpackSqlFile = backpackSqlFile;
       this.backpackBatFile = backpackBatFile;
       this.backpackToPath = backpackToPath;
    }
   
    public Integer getBackpackSettingId() {
        return this.backpackSettingId;
    }
    
    public void setBackpackSettingId(Integer backpackSettingId) {
        this.backpackSettingId = backpackSettingId;
    }
    public String getBackpackSqlFile() {
        return this.backpackSqlFile;
    }
    
    public void setBackpackSqlFile(String backpackSqlFile) {
        this.backpackSqlFile = backpackSqlFile;
    }
    public String getBackpackBatFile() {
        return this.backpackBatFile;
    }
    
    public void setBackpackBatFile(String backpackBatFile) {
        this.backpackBatFile = backpackBatFile;
    }
    public String getBackpackToPath() {
        return this.backpackToPath;
    }
    
    public void setBackpackToPath(String backpackToPath) {
        this.backpackToPath = backpackToPath;
    }




}


