package com.vector.pojo;
// Generated 2019-3-22 22:17:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CheckItem generated by hbm2java
 */
public class CheckItem  implements java.io.Serializable {


     private Integer checkItemId;
     private String checkItemName;
     private float checkItemPrice;
     private String checkItemDescription;
     private Set checkRecords = new HashSet(0);

    public CheckItem() {
    }

	
    public CheckItem(String checkItemName, float checkItemPrice, String checkItemDescription) {
        this.checkItemName = checkItemName;
        this.checkItemPrice = checkItemPrice;
        this.checkItemDescription = checkItemDescription;
    }
    public CheckItem(String checkItemName, float checkItemPrice, String checkItemDescription, Set checkRecords) {
       this.checkItemName = checkItemName;
       this.checkItemPrice = checkItemPrice;
       this.checkItemDescription = checkItemDescription;
       this.checkRecords = checkRecords;
    }
   
    public Integer getCheckItemId() {
        return this.checkItemId;
    }
    
    public void setCheckItemId(Integer checkItemId) {
        this.checkItemId = checkItemId;
    }
    public String getCheckItemName() {
        return this.checkItemName;
    }
    
    public void setCheckItemName(String checkItemName) {
        this.checkItemName = checkItemName;
    }
    public float getCheckItemPrice() {
        return this.checkItemPrice;
    }
    
    public void setCheckItemPrice(float checkItemPrice) {
        this.checkItemPrice = checkItemPrice;
    }
    public String getCheckItemDescription() {
        return this.checkItemDescription;
    }
    
    public void setCheckItemDescription(String checkItemDescription) {
        this.checkItemDescription = checkItemDescription;
    }
    public Set getCheckRecords() {
        return this.checkRecords;
    }
    
    public void setCheckRecords(Set checkRecords) {
        this.checkRecords = checkRecords;
    }




}


