package com.vector.pojo;
// Generated 2019-4-6 14:07:37 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CheckRecord generated by hbm2java
 */
public class CheckRecord  implements java.io.Serializable {


     private Integer checkRecordId;
     private CheckItem checkItem;
     private Patient patient;
     private Staff staff;
     private String paymentStatus;
     private Date checkDate;
     private String checkResultDescription;
     private String resultFile;

    public CheckRecord() {
    }

	
    public CheckRecord(CheckItem checkItem, Patient patient, Staff staff, String paymentStatus, Date checkDate, String checkResultDescription) {
        this.checkItem = checkItem;
        this.patient = patient;
        this.staff = staff;
        this.paymentStatus = paymentStatus;
        this.checkDate = checkDate;
        this.checkResultDescription = checkResultDescription;
    }
    public CheckRecord(CheckItem checkItem, Patient patient, Staff staff, String paymentStatus, Date checkDate, String checkResultDescription, String resultFile) {
       this.checkItem = checkItem;
       this.patient = patient;
       this.staff = staff;
       this.paymentStatus = paymentStatus;
       this.checkDate = checkDate;
       this.checkResultDescription = checkResultDescription;
       this.resultFile = resultFile;
    }
   
    public Integer getCheckRecordId() {
        return this.checkRecordId;
    }
    
    public void setCheckRecordId(Integer checkRecordId) {
        this.checkRecordId = checkRecordId;
    }
    public CheckItem getCheckItem() {
        return this.checkItem;
    }
    
    public void setCheckItem(CheckItem checkItem) {
        this.checkItem = checkItem;
    }
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }
    public Staff getStaff() {
        return this.staff;
    }
    
    public void setStaff(Staff staff) {
        this.staff = staff;
    }
    public String getPaymentStatus() {
        return this.paymentStatus;
    }
    
    public void setPaymentStatus(String paymentStatus) {
        this.paymentStatus = paymentStatus;
    }
    public Date getCheckDate() {
        return this.checkDate;
    }
    
    public void setCheckDate(Date checkDate) {
        this.checkDate = checkDate;
    }
    public String getCheckResultDescription() {
        return this.checkResultDescription;
    }
    
    public void setCheckResultDescription(String checkResultDescription) {
        this.checkResultDescription = checkResultDescription;
    }
    public String getResultFile() {
        return this.resultFile;
    }
    
    public void setResultFile(String resultFile) {
        this.resultFile = resultFile;
    }




}


