package com.vector.pojo;
// Generated 2019-3-22 22:17:21 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;

/**
 * Department generated by hbm2java
 */
public class Department implements java.io.Serializable {

    private Integer departmentId;
    private Image image;
    private String departmentName;
    private String departmentDescription;
    @JsonIgnore
    private Set staffs = new HashSet(0);

    public Department() {
    }

    public Department(Image image, String departmentName, String departmentDescription) {
        this.image = image;
        this.departmentName = departmentName;
        this.departmentDescription = departmentDescription;
    }

    public Department(Image image, String departmentName, String departmentDescription, Set staffs) {
        this.image = image;
        this.departmentName = departmentName;
        this.departmentDescription = departmentDescription;
        this.staffs = staffs;
    }

    public Integer getDepartmentId() {
        return this.departmentId;
    }

    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    public Image getImage() {
        return this.image;
    }

    public void setImage(Image image) {
        this.image = image;
    }

    public String getDepartmentName() {
        return this.departmentName;
    }

    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }

    public String getDepartmentDescription() {
        return this.departmentDescription;
    }

    public void setDepartmentDescription(String departmentDescription) {
        this.departmentDescription = departmentDescription;
    }

    public Set getStaffs() {
        return this.staffs;
    }

    public void setStaffs(Set staffs) {
        this.staffs = staffs;
    }

}
