package com.vector.pojo;
// Generated 2019-3-22 22:17:21 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * DietAdvice generated by hbm2java
 */
public class DietAdvice  implements java.io.Serializable {


     private Integer dietAdviceId;
     private Patient patient;
     private Staff staff;
     private String dietAdviceContent;
     private Date dietAdviceTime;

    public DietAdvice() {
    }

    public DietAdvice(Patient patient, Staff staff, String dietAdviceContent, Date dietAdviceTime) {
       this.patient = patient;
       this.staff = staff;
       this.dietAdviceContent = dietAdviceContent;
       this.dietAdviceTime = dietAdviceTime;
    }
   
    public Integer getDietAdviceId() {
        return this.dietAdviceId;
    }
    
    public void setDietAdviceId(Integer dietAdviceId) {
        this.dietAdviceId = dietAdviceId;
    }
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }
    public Staff getStaff() {
        return this.staff;
    }
    
    public void setStaff(Staff staff) {
        this.staff = staff;
    }
    public String getDietAdviceContent() {
        return this.dietAdviceContent;
    }
    
    public void setDietAdviceContent(String dietAdviceContent) {
        this.dietAdviceContent = dietAdviceContent;
    }
    public Date getDietAdviceTime() {
        return this.dietAdviceTime;
    }
    
    public void setDietAdviceTime(Date dietAdviceTime) {
        this.dietAdviceTime = dietAdviceTime;
    }




}


