package com.vector.pojo;
// Generated 2019-3-22 22:17:21 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;

/**
 * Image generated by hbm2java
 */
public class Image implements java.io.Serializable {

    private Integer imageId;
    private String imagePath;
    private String usePage;
    @JsonIgnore
    private Set patients = new HashSet(0);
    @JsonIgnore
    private Set departments = new HashSet(0);
    @JsonIgnore
    private Set staffs = new HashSet(0);

    public Image() {
    }

    public Image(String imagePath) {
        this.imagePath = imagePath;
    }

    public Image(String imagePath, String usePage, Set patients, Set departments, Set staffs) {
        this.imagePath = imagePath;
        this.usePage = usePage;
        this.patients = patients;
        this.departments = departments;
        this.staffs = staffs;
    }

    public Integer getImageId() {
        return this.imageId;
    }

    public void setImageId(Integer imageId) {
        this.imageId = imageId;
    }

    public String getImagePath() {
        return this.imagePath;
    }

    public void setImagePath(String imagePath) {
        this.imagePath = imagePath;
    }

    public String getUsePage() {
        return this.usePage;
    }

    public void setUsePage(String usePage) {
        this.usePage = usePage;
    }

    public Set getPatients() {
        return this.patients;
    }

    public void setPatients(Set patients) {
        this.patients = patients;
    }

    public Set getDepartments() {
        return this.departments;
    }

    public void setDepartments(Set departments) {
        this.departments = departments;
    }

    public Set getStaffs() {
        return this.staffs;
    }

    public void setStaffs(Set staffs) {
        this.staffs = staffs;
    }

}
