package com.vector.pojo;
// Generated 2019-3-22 22:17:21 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MedicalRecord generated by hbm2java
 */
public class MedicalRecord  implements java.io.Serializable {


     private Integer medicalRecordId;
     private Patient patient;
     private Staff staff;
     private String diagnosticDescription;
     private Date date;
     private String symptom;
     private Set prescriptions = new HashSet(0);

    public MedicalRecord() {
    }

	
    public MedicalRecord(Patient patient, Staff staff, String diagnosticDescription, Date date) {
        this.patient = patient;
        this.staff = staff;
        this.diagnosticDescription = diagnosticDescription;
        this.date = date;
    }
    public MedicalRecord(Patient patient, Staff staff, String diagnosticDescription, Date date, String symptom, Set prescriptions) {
       this.patient = patient;
       this.staff = staff;
       this.diagnosticDescription = diagnosticDescription;
       this.date = date;
       this.symptom = symptom;
       this.prescriptions = prescriptions;
    }
   
    public Integer getMedicalRecordId() {
        return this.medicalRecordId;
    }
    
    public void setMedicalRecordId(Integer medicalRecordId) {
        this.medicalRecordId = medicalRecordId;
    }
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }
    public Staff getStaff() {
        return this.staff;
    }
    
    public void setStaff(Staff staff) {
        this.staff = staff;
    }
    public String getDiagnosticDescription() {
        return this.diagnosticDescription;
    }
    
    public void setDiagnosticDescription(String diagnosticDescription) {
        this.diagnosticDescription = diagnosticDescription;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getSymptom() {
        return this.symptom;
    }
    
    public void setSymptom(String symptom) {
        this.symptom = symptom;
    }
    public Set getPrescriptions() {
        return this.prescriptions;
    }
    
    public void setPrescriptions(Set prescriptions) {
        this.prescriptions = prescriptions;
    }




}


