package com.vector.pojo;
// Generated 2019-4-17 11:06:27 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PrecautionAdvice generated by hbm2java
 */
public class PrecautionAdvice  implements java.io.Serializable {


     private int precautionAdviceId;
     private Patient patient;
     private PrecautionAdvice precautionAdvice;
     private Staff staff;
     private String precautionAdviceContent;
     private Date dietAdviceTime;
     @JsonIgnore
     private Set precautionAdvices = new HashSet(0);

    public PrecautionAdvice() {
    }

	
    public PrecautionAdvice(int precautionAdviceId, Patient patient, Staff staff, String precautionAdviceContent, Date dietAdviceTime) {
        this.precautionAdviceId = precautionAdviceId;
        this.patient = patient;
        this.staff = staff;
        this.precautionAdviceContent = precautionAdviceContent;
        this.dietAdviceTime = dietAdviceTime;
    }
    public PrecautionAdvice(int precautionAdviceId, Patient patient, PrecautionAdvice precautionAdvice, Staff staff, String precautionAdviceContent, Date dietAdviceTime, Set precautionAdvices) {
       this.precautionAdviceId = precautionAdviceId;
       this.patient = patient;
       this.precautionAdvice = precautionAdvice;
       this.staff = staff;
       this.precautionAdviceContent = precautionAdviceContent;
       this.dietAdviceTime = dietAdviceTime;
       this.precautionAdvices = precautionAdvices;
    }
   
    public int getPrecautionAdviceId() {
        return this.precautionAdviceId;
    }
    
    public void setPrecautionAdviceId(int precautionAdviceId) {
        this.precautionAdviceId = precautionAdviceId;
    }
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }
    public PrecautionAdvice getPrecautionAdvice() {
        return this.precautionAdvice;
    }
    
    public void setPrecautionAdvice(PrecautionAdvice precautionAdvice) {
        this.precautionAdvice = precautionAdvice;
    }
    public Staff getStaff() {
        return this.staff;
    }
    
    public void setStaff(Staff staff) {
        this.staff = staff;
    }
    public String getPrecautionAdviceContent() {
        return this.precautionAdviceContent;
    }
    
    public void setPrecautionAdviceContent(String precautionAdviceContent) {
        this.precautionAdviceContent = precautionAdviceContent;
    }
    public Date getDietAdviceTime() {
        return this.dietAdviceTime;
    }
    
    public void setDietAdviceTime(Date dietAdviceTime) {
        this.dietAdviceTime = dietAdviceTime;
    }
    public Set getPrecautionAdvices() {
        return this.precautionAdvices;
    }
    
    public void setPrecautionAdvices(Set precautionAdvices) {
        this.precautionAdvices = precautionAdvices;
    }




}


