package com.vector.pojo;
// Generated 2019-3-31 10:57:37 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Reservation generated by hbm2java
 */
public class Reservation  implements java.io.Serializable {


     private Integer reservationId;
     private Patient patient;
     private Staff staff;
     private String reservationTime;
     private Date reservationDate;
     private String isFinished;

    public Reservation() {
    }

    public Reservation(Patient patient, Staff staff, String reservationTime, Date reservationDate, String isFinished) {
       this.patient = patient;
       this.staff = staff;
       this.reservationTime = reservationTime;
       this.reservationDate = reservationDate;
       this.isFinished = isFinished;
    }
   
    public Integer getReservationId() {
        return this.reservationId;
    }
    
    public void setReservationId(Integer reservationId) {
        this.reservationId = reservationId;
    }
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }
    public Staff getStaff() {
        return this.staff;
    }
    
    public void setStaff(Staff staff) {
        this.staff = staff;
    }
    public String getReservationTime() {
        return this.reservationTime;
    }
    
    public void setReservationTime(String reservationTime) {
        this.reservationTime = reservationTime;
    }
    public Date getReservationDate() {
        return this.reservationDate;
    }
    
    public void setReservationDate(Date reservationDate) {
        this.reservationDate = reservationDate;
    }
    public String getIsFinished() {
        return this.isFinished;
    }
    
    public void setIsFinished(String isFinished) {
        this.isFinished = isFinished;
    }




}


