package com.vector.pojo;
// Generated 2019-3-30 11:03:05 by Hibernate Tools 4.3.1



/**
 * Reservation generated by hbm2java
 */
public class Reservation  implements java.io.Serializable {


     private Integer reservationId;
     private Patient patient;
     private Staff staff;
     private String reservationTime;

    public Reservation() {
    }

    public Reservation(Patient patient, Staff staff, String reservationTime) {
       this.patient = patient;
       this.staff = staff;
       this.reservationTime = reservationTime;
    }
   
    public Integer getReservationId() {
        return this.reservationId;
    }
    
    public void setReservationId(Integer reservationId) {
        this.reservationId = reservationId;
    }
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }
    public Staff getStaff() {
        return this.staff;
    }
    
    public void setStaff(Staff staff) {
        this.staff = staff;
    }
    public String getReservationTime() {
        return this.reservationTime;
    }
    
    public void setReservationTime(String reservationTime) {
        this.reservationTime = reservationTime;
    }




}


