package com.vector.pojo;
// Generated 2019-3-22 22:17:21 by Hibernate Tools 4.3.1



/**
 * Task generated by hbm2java
 */
public class Task  implements java.io.Serializable {


     private Integer taskId;
     private Patient patient;
     private Staff staffByTaskSponsor;
     private Staff staffByTaskTarget;
     private String taskContent;
     private String taskStatus;
     private float taskProgress;

    public Task() {
    }

    public Task(Patient patient, Staff staffByTaskSponsor, Staff staffByTaskTarget, String taskContent, String taskStatus, float taskProgress) {
       this.patient = patient;
       this.staffByTaskSponsor = staffByTaskSponsor;
       this.staffByTaskTarget = staffByTaskTarget;
       this.taskContent = taskContent;
       this.taskStatus = taskStatus;
       this.taskProgress = taskProgress;
    }
   
    public Integer getTaskId() {
        return this.taskId;
    }
    
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }
    public Staff getStaffByTaskSponsor() {
        return this.staffByTaskSponsor;
    }
    
    public void setStaffByTaskSponsor(Staff staffByTaskSponsor) {
        this.staffByTaskSponsor = staffByTaskSponsor;
    }
    public Staff getStaffByTaskTarget() {
        return this.staffByTaskTarget;
    }
    
    public void setStaffByTaskTarget(Staff staffByTaskTarget) {
        this.staffByTaskTarget = staffByTaskTarget;
    }
    public String getTaskContent() {
        return this.taskContent;
    }
    
    public void setTaskContent(String taskContent) {
        this.taskContent = taskContent;
    }
    public String getTaskStatus() {
        return this.taskStatus;
    }
    
    public void setTaskStatus(String taskStatus) {
        this.taskStatus = taskStatus;
    }
    public float getTaskProgress() {
        return this.taskProgress;
    }
    
    public void setTaskProgress(float taskProgress) {
        this.taskProgress = taskProgress;
    }




}


