package com.vector.pojo;
// Generated 2019-3-22 22:17:21 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;

/**
 * Title generated by hbm2java
 */
public class Title  implements java.io.Serializable {


     private Integer titleId;
     private String titleName;
     private String titleDescription;
     @JsonIgnore
     private Set staffs = new HashSet(0);

    public Title() {
    }

	
    public Title(String titleName) {
        this.titleName = titleName;
    }
    public Title(String titleName, String titleDescription, Set staffs) {
       this.titleName = titleName;
       this.titleDescription = titleDescription;
       this.staffs = staffs;
    }
   
    public Integer getTitleId() {
        return this.titleId;
    }
    
    public void setTitleId(Integer titleId) {
        this.titleId = titleId;
    }
    public String getTitleName() {
        return this.titleName;
    }
    
    public void setTitleName(String titleName) {
        this.titleName = titleName;
    }
    public String getTitleDescription() {
        return this.titleDescription;
    }
    
    public void setTitleDescription(String titleDescription) {
        this.titleDescription = titleDescription;
    }
    public Set getStaffs() {
        return this.staffs;
    }
    
    public void setStaffs(Set staffs) {
        this.staffs = staffs;
    }




}


